- repository: autowarefoundation/autoware
  files:
    - source: CODE_OF_CONDUCT.md
    - source: CONTRIBUTING.md
    - source: DISCLAIMER.md
    - source: LICENSE
    - source: .github/ISSUE_TEMPLATE/bug.yaml
    - source: .github/ISSUE_TEMPLATE/config.yml
    - source: .github/ISSUE_TEMPLATE/task.yaml
    - source: .github/PULL_REQUEST_TEMPLATE.md
    - source: .github/PULL_REQUEST_TEMPLATE/small-change.md
    - source: .github/PULL_REQUEST_TEMPLATE/standard-change.md
    - source: .github/stale.yml
    - source: .github/workflows/github-release.yaml
    - source: .github/workflows/pre-commit.yaml
    - source: .github/workflows/pre-commit-optional.yaml
    - source: .github/workflows/spell-check-differential.yaml
    - source: .github/workflows/sync-files.yaml
    - source: .markdown-link-check.json
    - source: .markdownlint.yaml
    - source: .pre-commit-config.yaml
      pre-command: |
        echo 111
        cat {dest}
        echo 222
      post-command: |
        echo 333
        sd -f ms "[^\n]*shellcheck-py\n.*?\n\n" "" {dest}
        echo 444
    - source: .pre-commit-config-optional.yaml
    - source: .prettierignore
    - source: .prettierrc.yaml
    - source: .yamllint.yaml
    - source: README.md
      pre-command: |
        echo 555
        title=$(cat {source} | head -n1)
        echo "$title"
        echo 666
      post-command: |
        echo 777
        sed -i "s/Autoware/foo/g" {dest}
        sed -i "s/^# .*/$title/g" {dest}
        echo 888
    - source: NOTICE
      dest: foo.md
      pre-command: |
        echo 999
        cat {dest}
        echo 000
