name: pre-commit
description: ""

inputs:
  pre-commit-config:
    description: ""
    required: true
  base-branch:
    description: ""
    required: false
  token:
    description: ""
    required: false
    default: ${{ github.token }}

runs:
  using: composite
  steps:
    - name: Set git config
      uses: autowarefoundation/autoware-github-actions/set-git-config@v1
      with:
        token: ${{ inputs.token }}

    - name: Set option
      id: set-option
      run: |
        if [ -z "${{ inputs.base-branch }}" ]; then
          echo "option=--all-files" >> $GITHUB_OUTPUT
          exit 0
        fi
        echo "option=--from-ref ${{ inputs.base-branch }} --to-ref HEAD" >> $GITHUB_OUTPUT
      shell: bash

    - name: Run pre-commit
      uses: pre-commit/action@v3.0.1
      with:
        extra_args: --config ${{ inputs.pre-commit-config }} ${{ steps.set-option.outputs.option }}

    - name: Push pre-commit fixes
      if: always() # Push changes even when pre-commit fails
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "style(pre-commit): autofix"
        add_options: -u
