name: get-self-packages
description: ""

outputs:
  self-packages:
    description: ""
    value: ${{ steps.get-self-packages.outputs.self-packages }}

runs:
  using: composite
  steps:
    - name: Get packages in this repository
      id: get-self-packages
      run: |
        self_packages=$(colcon list --names-only)
        echo "self-packages=$(printf "%s " $self_packages | sed 's/\s*$//')" >> $GITHUB_OUTPUT
      shell: bash

    - name: Show result
      run: |
        echo "self-packages: ${{ steps.get-self-packages.outputs.self-packages }}"
      shell: bash
