complete -c git-cliff -n "__fish_use_subcommand" -s c -l config -d 'Sets the configuration file'
complete -c git-cliff -n "__fish_use_subcommand" -s w -l workdir -d 'Sets the working directory'
complete -c git-cliff -n "__fish_use_subcommand" -s r -l repository -d 'Sets the git repository'
complete -c git-cliff -n "__fish_use_subcommand" -l include-path -d 'Sets the path to include related commits'
complete -c git-cliff -n "__fish_use_subcommand" -l exclude-path -d 'Sets the path to exclude related commits'
complete -c git-cliff -n "__fish_use_subcommand" -l with-commit -d 'Sets custom commit messages to include in the changelog'
complete -c git-cliff -n "__fish_use_subcommand" -s p -l prepend -d 'Prepends entries to the given changelog file'
complete -c git-cliff -n "__fish_use_subcommand" -s o -l output -d 'Writes output to the given file'
complete -c git-cliff -n "__fish_use_subcommand" -s t -l tag -d 'Sets the tag for the latest version'
complete -c git-cliff -n "__fish_use_subcommand" -s b -l body -d 'Sets the template for the changelog body'
complete -c git-cliff -n "__fish_use_subcommand" -s s -l strip -d 'Strips the given parts from the changelog' -r -f -a "header footer all"
complete -c git-cliff -n "__fish_use_subcommand" -l sort -d 'Sets sorting of the commits inside sections' -r -f -a "oldest newest"
complete -c git-cliff -n "__fish_use_subcommand" -s v -l verbose -d 'Increases the logging verbosity'
complete -c git-cliff -n "__fish_use_subcommand" -s i -l init -d 'Writes the default configuration file to cliff.toml'
complete -c git-cliff -n "__fish_use_subcommand" -s l -l latest -d 'Processes the commits starting from the latest tag'
complete -c git-cliff -n "__fish_use_subcommand" -l current -d 'Processes the commits that belong to the current tag'
complete -c git-cliff -n "__fish_use_subcommand" -s u -l unreleased -d 'Processes the commits that do not belong to a tag'
complete -c git-cliff -n "__fish_use_subcommand" -l topo-order -d 'Sorts the tags topologically'
complete -c git-cliff -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c git-cliff -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
