name: check-file-existence
description: ""

inputs:
  files:
    description: ""
    required: true
  condition:
    description: ""
    required: false
    default: and
outputs:
  exists:
    description: ""
    value: ${{ steps.check-file-existence.outputs.exists }}

runs:
  using: composite
  steps:
    - name: File check
      id: check-file-existence
      run: |
        set -e

        # Split files into an array
        tmp="${{ inputs.files }}"
        input_files=(${tmp})

        # Iterate files
        found_files=()
        for f in "${input_files[@]}"; do
          if [[ -f $f ]]; then
            echo "File exists: $f"
            found_files+=("$f")
          else
            echo "File does not exist: $f"
          fi
        done

        num_found_files=${#found_files[@]}
        if [[ "${{ inputs.condition }}" = "or" ]]; then
          if [[ "$num_found_files" -gt 0 ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        elif [[ "${{ inputs.condition }}" = "and" ]]; then
          num_input_files=${#input_files[@]}
          if [[ "$num_found_files" -eq "$num_input_files" ]]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        else
          echo "exists=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
