name: set-cuda-path
description: ""

runs:
  using: composite
  steps:
    - name: Set CUDA path
      run: |
        CUDA_PATH=/usr/local/cuda
        echo "CUDA_PATH=${CUDA_PATH}" >> $GITHUB_ENV
        echo "${CUDA_PATH}/bin" >> $GITHUB_PATH
        echo "LD_LIBRARY_PATH=${CUDA_PATH}/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
      shell: bash
