name: test-composite-actions

on:
  pull_request:

jobs:
  test-register-autonomoustuff-repository:
    runs-on: ubuntu-latest
    container: ros:${{ matrix.rosdistro }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - galactic
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run register-autonomoustuff-repository
        uses: ./register-autonomoustuff-repository
        with:
          rosdistro: ${{ matrix.rosdistro }}

      - name: Install pacmod3_msgs
        run: |
          sudo apt-get install -y ros-${{ matrix.rosdistro }}-pacmod3-msgs

      - name: Check rosdep
        run: |
          rosdep update
          rosdep resolve pacmod3_msgs

  test-clang-tidy-empty-target:
    runs-on: ubuntu-latest
    container: ros:${{ matrix.rosdistro }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - galactic
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create a package with no source files
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh
          ros2 pkg create empty_target

      - name: Run clang-tidy
        uses: ./clang-tidy
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: empty_target
          clang-tidy-config-url: https://raw.githubusercontent.com/autowarefoundation/autoware/tier4/proposal/.clang-tidy

  test-colcon-build-and-test:
    runs-on: ubuntu-latest
    container: ros:${{ matrix.rosdistro }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - galactic
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create a package with no source files
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh
          ros2 pkg create --build-type ament_cmake empty_target_cmake
          ros2 pkg create --build-type ament_python empty_target_python

      - name: Run colcon-build-and-test
        uses: ./colcon-build-and-test
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: empty_target_cmake empty_target_python

  test-check-file-existence:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create temporary files
        run: |
          touch foo
          touch bar

      - name: Run check-file-existence
        id: check-file-existence1
        uses: ./check-file-existence
        with:
          files: |
            foo
            bar
          condition: and

      - name: Check result
        run: |
          [[ "${{ steps.check-file-existence1.outputs.exists }}" == "true" ]]

      - name: Run check-file-existence
        id: check-file-existence2
        uses: ./check-file-existence
        with:
          files: |
            foo
            bar
            baz
          condition: and

      - name: Check result
        run: |
          [[ "${{ steps.check-file-existence2.outputs.exists }}" == "false" ]]

      - name: Run check-file-existence
        id: check-file-existence3
        uses: ./check-file-existence
        with:
          files: foo
          condition: or

      - name: Check result
        run: |
          [[ "${{ steps.check-file-existence3.outputs.exists }}" == "true" ]]

      - name: Run check-file-existence
        id: check-file-existence4
        uses: ./check-file-existence
        with:
          files: |
            foo
            baz
          condition: or

      - name: Check result
        run: |
          [[ "${{ steps.check-file-existence4.outputs.exists }}" == "true" ]]

  test-colcon-build-and-colcon-test:
    runs-on: ubuntu-latest
    container: ros:${{ matrix.rosdistro }}
    strategy:
      fail-fast: false
      matrix:
        rosdistro:
          - galactic
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create a package with no source files
        run: |
          . /opt/ros/${{ matrix.rosdistro }}/setup.sh
          ros2 pkg create --build-type ament_cmake empty_target_cmake
          ros2 pkg create --build-type ament_python empty_target_python

      - name: Run colcon-build
        uses: ./colcon-build
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: empty_target_cmake empty_target_python

      - name: Run colcon-test
        uses: ./colcon-test
        with:
          rosdistro: ${{ matrix.rosdistro }}
          target-packages: empty_target_cmake empty_target_python
